apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      #serviceaccount: backstage
      imagePullSecrets:
        - name: backstage-docker-auth2
      containers:
        - name: backstage
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 1Gi
              cpu: 500m
          image: ghcr.io/paulopanini/backstage:20231002111614
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: GITHUB_TOKEN
              value: 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
          envFrom:
            - secretRef:
                name: backstage-secrets
            
            
# Uncomment if health checks are enabled in your app:
# https://backstage.io/docs/plugins/observability#health-checks
#          readinessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
#          livenessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
