apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      #serviceaccount: backstage
      imagePullSecrets:
        - name: backstage-docker-auth2
      containers:
        - name: backstage
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 1Gi
              cpu: 500m
          image: ghcr.io/paulopanini/backstage:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-git-access-token
                  key: token
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-db-pguser-backstage-db
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-db-pguser-backstage-db
                  key: password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: backstage-db-pguser-backstage-db
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: backstage-db-pguser-backstage-db
                  key: port
# Uncomment if health checks are enabled in your app:
# https://backstage.io/docs/plugins/observability#health-checks
#          readinessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
#          livenessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
